const langs = {
  en: {
    title: "ShopKart",
    categories: "Category",
    wishlist: "Wishlist",
    categoriesTitle: "Categories to bag",
    heroTag: "A few clicks is all it takes",
    menClothing: "Men Clothing",
    womenClothing: "Women Clothing",
    electronics: "Electronics",
    jewelry: "Jewelry",
    copyright: "© Copyright 2021. All Rights Reserved.",
    searchTitle: "Search",
    English: "En - English",
    Español: "Es - Español",
    AppleDownloadTextOne: "Download on the",
    AppleDownloadTextTwo: "Apple Store",
    GoogleDownloadTextOne: "Download it from",
    GoogleDownloadTextTwo: "Google play",
    // Pages
    Products: "Products",
    Size: "Size",
    Quantity: "Quantity",
    MoveToWishList: "Move to wishlist",
    Remove: "Remove",
    Price: "Price",
    Coupons: "Coupons",
    GiftingAndPersonalization: "gifting and personalization",
    BuyingForLovedOnes: "Buying for loved ones ?",
    GiftWrap: "Gift wrapped and personalized message on card , Only for $ 25",
    AddGiftWrap: "Add gift wrap",
    PlaceOrder: "Place order",
    Apply: "Apply",
    ApplyCoupons: "ApplyCoupons",
    TotalMRP: "Total MRP",
    DiscountOnMRP: "Discount on MRP",
    CouponDiscount: "Coupon Discount",
    //
    orderHistory: "Order History",
    trackOrder: "Track Order",
    contactUs: "Contact Us",
    editProfile: "Edit Profile",
    login: "Login",
    signUp: "Sign Up",
    profileGreet: "To access account and",
    manageOrder: "manage orders",
    loginTitle: "Welcome to Shopkart",
    loginSubTitle: "Join / Sign in using",
    mobileLabel: "Enter a Mobile Number",
    loginButton: "Continue",
    loginFooter: "By Signing In, I agree to",
    toc: "Terms and Conditions",
  },
  sp: {
    title: "ShopKart",
    categories: "Categoría",
    wishlist: "Lista de deseos",
    categoriesTitle: "Categorías para empacar",
    heroTag: "Unos pocos clics es todo lo que necesita",
    menClothing: "Ropa de hombre",
    womenClothing: "Ropa de mujeres",
    electronics: "Electrónica",
    jewelry: "Joyas",
    copyright: "© Derechos de autor 2021. Todos los derechos reservados.",
    searchTitle: "buscar",
    manageOrder: "administrar pedidos",
    English: "En - Inglés",
    Español: "Es - Español",
    AppleDownloadTextOne: "Descargar en la tienda",
    AppleDownloadTextTwo: "de Apple",
    GoogleDownloadTextOne: "Descárgalo de ",
    GoogleDownloadTextTwo: "Google play",
    //pages
    products: "productos",
    Size: "Tamaño",
    Quantity: "Cantidad",
    MoveToWishList: "Mover a la lista de deseos",
    Remove: "Eliminar",
    Price: "Precio",
    Coupons: "Cupones",
    GiftingAndPersonalization: "regalos y personalización",
    BuyingForLovedOnes: "¿Comprando para sus seres queridos?",
    GiftWrap:
      "Envuelto para regalo y mensaje personalizado en la tarjeta, solo por $ 25",
    AddGiftWrap: "Agregar papel de regalo",
    PlaceOrder: "Realizar pedido",
    Apply: "Aplicar",
    ApplyCoupons: "Aplicar Cupones",
    TotalMRP: "MRP total",
    DiscountOnMRP: "Descuento en MRP",
    CouponDiscount: "Cupón de descuento",
    //
    orderHistory: "Historial de pedidos",
    trackOrder: "Orden de pista",
    contactUs: "Contacta con nosotras",
    editProfile: "Editar perfil",
    login: "Acceso",
    signUp: "Inscribirse",
    profileGreet: "Para acceder a la cuenta y administrar pedidos",
    loginTitle: "Bienvenido a ShopKart",
    loginSubTitle: "Unirse / Iniciar sesión usando",
    mobileLabel: "Ingrese un número de celular",
    loginButton: "Continuar",
    loginFooter: "Al iniciar sesión, acepto",
    toc: "Términos y condiciones",
  },
};

export { langs };
